### ISSUE TITLE
Forgotten main.c

### ISSUE THREAD

**Issue by oz123** [gnudles/wkgtkprinter#3]
Hey,
`main.c` ins't included. Once it is, I guess #1 can be closed too.

**Comment by gnudles** [comment]
oh my! once again forgot to 'git add' it

**Comment by oz123** [comment]
![image](https://user-images.githubusercontent.com/1083045/163461042-a82d4398-d3cc-4269-ada2-2e4f72a30d1e.png)

Use a git colorful prompt to the rescue here :-) The red X says I have untracked files.

**Comment by gnudles** [comment]
Btw, The main is very very basic. If one has the time to improve it, he is more than welcome... Need to add help (-h). The html string is passed through stdin, other stuff passed as files or uri, very similar to the c function..

**Comment by oz123** [comment]
I could give it a shot, but it is still missing :-)

**Comment by gnudles** [comment]
There  it is :)
Thank you very mucho :)

**Comment by gnudles** [comment]
Also need to update the README accordingly. I'm not that good at fitting to the standard of open source project :\ 
It took me much time to figure out how to do the printing in webkit-gtk... There is no good documentation for that purpose.
And I wish more people could join me to make this project better.
